### ISSUE TITLE
Add encoding to DOCUMENTATION ->html output

### ISSUE THREAD

**Issue by perNyfelt** [jimschubert/intellij-swagger-codegen#13]
Please add a <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> to the head section of the html generated by the DOCUMENTATION -> html task so that characters such as åäö can be used in the descriptions e.g. 
properties:
      firstName:
        description: Given name (Förnamn)
        type: string
        example: Per

**Comment by jimschubert** [comment]
Can you provide an example?

This project just proxies options to Swagger Codegen, then invokes Swagger Codegen  to generate output. I would assume that any encoding issues would be in Swagger Codegen.

Is it simply that you have these UTF-8 characters in some model properties, and they're not output? Or are they in the swagger definitions info?

Would you be willing to run directly against Swagger Codegen to see if you still have the issue? I have a helper script here: https://gist.github.com/jimschubert/62baf653a9520b23399a67755c33631a

**Comment by jimschubert** [comment]
@perNyfelt I haven't heard back, so I'm going to close this as I assume the issue has been resolved. Please open an issue at Swagger Codegen for options/bugs in individual generators.
